"""
build_problem_readme.py
-----------------------
Scans all problem.json files in the repo and generates a README.md
for each problem folder, only if solved is true.
Run by GitHub Actions on every push to main.
"""
 
import json
import os
 
 
def load_all_problems(root: str = ".") -> list[dict]:
    problems = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d != "template"]
        if "problem.json" in filenames:
            json_path = os.path.join(dirpath, "problem.json")
            with open(json_path, "r") as f:
                data = json.load(f)
            data["_dirpath"] = dirpath
            problems.append(data)
    return problems

def read_file(dirpath: str, filename: str, stop_at: str = None) -> str:
    path = os.path.join(dirpath, filename)
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        if stop_at:
            idx = content.find(stop_at)
            if idx != -1:
                content = content[:idx + len(stop_at)]
        return content
    return "_File not found._"
 
 
def build_problem_readme(p: dict) -> str:
    title        = p.get("title", "Unknown")
    link         = p.get("link", "#")
    difficulty   = p.get("difficulty", "Unknown")
    topic        = p.get("topic", "Unknown").replace("_", " ").title()
    statement    = p.get("problem statement", "")
    approach     = p.get("approach", "")
    time_c       = p.get("time_complexity", "")
    space_c      = p.get("space_complexity", "")
 
    lines = [
        f"# {title}",
        "",
        f"**Difficulty:** {difficulty}  ",
        f"**Topic:** {topic}  ",
        f"**Link:** [LeetCode]({link})",
        "",
        "",
        "## Problem Statement",
        "",
        statement if statement else "_No problem statement added yet._",
        "",
        "",
        "## Approach",
        "",
        approach if approach else "_No approach added yet._",
        "",
        "",
        "## Solution",
        "",
        "```python",
        read_file(p["_dirpath"], "solution.py"),
        "```",
        "",
        "",
        "## Test Cases",
        "",
        "```python",
        read_file(p["_dirpath"], "testcases.py", stop_at='print("All tests passed!")'),
        "```",
        "",
        "",
        "## Complexity",
        "",
        f"| Time | `{time_c if time_c else '?'}` |",
        f"| Space | `{space_c if space_c else '?'}` |",
        "",
        "",
        "---",
        "_Auto-generated by GitHub Actions._",
    ]
 
    return "\n".join(lines) + "\n"
 
 
if __name__ == "__main__":
    problems = load_all_problems()
    generated = 0
    skipped = 0
 
    for p in problems:
        if p.get("solved") is not True:
            skipped += 1
            continue

        
        readme_path = os.path.join(p["_dirpath"], "README.md")
        if os.path.isfile(readme_path):
            print(f"  Skipped (already exists): {readme_path}")
            skipped += 1
            continue
    
        readme = build_problem_readme(p)
        readme_path = os.path.join(p["_dirpath"], "README.md")
 
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme)
 
        print(f"  Generated: {readme_path}")
        generated += 1
 
    print(f"Done — {generated} generated, {skipped} skipped")