"""
build_main_readme.py
--------------------
Scans all problem.json files in the repo and regenerates the root README.md.
Run by GitHub Actions on every push to main.
"""
 
import json
import os
from collections import defaultdict
from datetime import datetime
 

TARGET = 150
 
 
# loads all problems
def load_all_problems(root: str = ".") -> list[dict]:
    problems = []
    for dirpath, dirnames, filenames in os.walk(root):
        # skip the template folder
        dirnames[:] = [d for d in dirnames if d != "template"]
        if "problem.json" in filenames:
            json_path = os.path.join(dirpath, "problem.json")
            with open(json_path, "r") as f:
                data = json.load(f)
            # derive topic and problem folder from the path
            parts = os.path.normpath(dirpath).split(os.sep)
            data["_topic_folder"] = parts[-2]
            data["_problem_folder"] = parts[-1]
            problems.append(data)
    return problems
 

def build_progress_bar(current: int, target: int, width: int = 30) -> str:
    filled = int(width * min(current, target) / target)
    bar = "█" * filled + "░" * (width - filled)
    pct = round(100 * current / target, 1)
    return f"`{bar}` {pct}%"
 
 
def build_readme(problems: list[dict]) -> str:
    total = len(problems)
    solved = sum(1 for p in problems if p.get("solved") is True)
 
    diff_counts = defaultdict(int)
    topic_counts = defaultdict(int)
    for p in problems:
        diff_counts[p.get("difficulty", "Unknown")] += 1
        topic_counts[p.get("_topic_folder", "unknown")] += 1
 
    lines = [
        "# LeetCode Practice",
        f" Just a repo used to track my LeetCode progress and to motivate me to do more (done in Python) with the goal to solve {TARGET} problems",
        "",
        f"> Auto-generated · Last updated: {datetime.now().strftime('%Y-%m-%d')}",
        "",
        "",
        f"## Progress — {solved} / {TARGET} solved",
        "",
        build_progress_bar(solved, TARGET),
        "",
        "",
        "## How I Use This Repo",
        "",
        "1. Find a problem on LeetCode",
        "2. Copy the details into `problem.json` and explain my approach in there",
        "3. Write the solution in `solution.py`",
        "4. Write the test cases in `testcases.py`",
        "5. Commit to trigger GitHub Actions and auto-generate/update the README(s)",
        "",
    ]

    if problems: 
        # topics table 
        lines += [
            "",
            "## Topics",
            "",
            "| Topic | Problems |",
            "|-------|----------|",
        ]
    
        for topic, count in sorted(topic_counts.items()):
            display = topic.replace("_", " ").title()
            lines.append(f"| {display} | {count} |")
    
        # problems table 

        lines += [
            "",
            "",
            "## All Problems",
            "",
            "| # | Problem | Topic | Difficulty | Solved |",
            "|---|---------|-------|------------|--------|",
        ]
    
        for i, p in enumerate(problems, 1):
            title = p.get("title", "Unknown")
            topic = p.get("topic", "Unknown").replace("_", " ").title()
            difficulty = p.get("difficulty", "Unknown")
            solved_mark = "Yes" if p.get("solved") is True else "No"
            folder = p.get("_problem_folder", "")
            topic_folder = p.get("topic", "unknown")
            readme_link = f"./{topic_folder}/{folder}/README.md"
    
            lines.append(f"| {i} | [{title}]({readme_link}) | {topic} | {difficulty} | {solved_mark} |")
    
        
    
        # difficulty table
        lines += [
            "",
            "",
            "## Difficulty Breakdown",
            "",
            "| Difficulty | Count |",
            "|------------|-------|",
        ]
    
        for d in ["easy", "medium", "hard"]:
            lines.append(f"| {d} | {diff_counts.get(d, 0)} |")
        lines.append(f"| **Total** | **{total}** |")

    lines += [
        "",
        "",
        "---",
        "_This README is auto-generated by GitHub Actions. Do not edit manually._",
    ]
 
    return "\n".join(lines) + "\n"
 
 
if __name__ == "__main__":
    problems = load_all_problems()
    print(f"Found {len(problems)} problem(s)")
    readme = build_readme(problems)
    with open("README.md", "w",encoding="utf-8") as f:
        f.write(readme)
    print("README.md updated")